### ISSUE TITLE
after defining a river getting the following error message:

### ISSUE THREAD

**Issue by yuvalk** [lbroudoux/es-amazon-s3-river#34]
failed to create river [amazon-s3][mys3docs]
org.elasticsearch.common.settings.NoClassSettingsException: Failed to load class with value [amazon-s3]
	at org.elasticsearch.river.RiverModule.loadTypeModule(RiverModule.java:87)
	at org.elasticsearch.river.RiverModule.spawnModules(RiverModule.java:58)
	at org.elasticsearch.common.inject.ModulesBuilder.add(ModulesBuilder.java:44)
	at org.elasticsearch.river.RiversService.createRiver(RiversService.java:137)
	at org.elasticsearch.river.RiversService$ApplyRivers$2.onResponse(RiversService.java:273)
	at org.elasticsearch.river.RiversService$ApplyRivers$2.onResponse(RiversService.java:267)
	at org.elasticsearch.action.support.TransportAction$ThreadedActionListener$1.run(TransportAction.java:113)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: amazon-s3
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.elasticsearch.river.RiverModule.loadTypeModule(RiverModule.java:73)
	... 9 more

**Comment by yuvalk** [comment]
hmm
probably my fault, trying to run 1.4 on 1.5 elasticsearch..

**Comment by yuvalk** [comment]
sorry, still happens even with 1.4.5
